# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

language: python 3.6
cache: pip

script:
  - ./test/dongbei_test.py && ./src/dongbei.py demo/*.dongbei
